# Regulatory Relevance Idenitification for Business Processes
--> retrieving potentially relevant text passages based on input query (process text)

1. semantic search with `SentenceTransformer('multi-qa-MiniLM-L6-cos-v1')`
2. re-ranking with CrossEncoder (`cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')`)

adjusted from:
https://www.sbert.net/examples/applications/retrieve_rerank/README.html

Scores to set expectations - COLIEE results 2023: https://sites.ualberta.ca/~rabelo/COLIEE2023/task1_results.html

In [1]:
!pip install -U sentence-transformers rank_bm25

Collecting sentence-transformers
  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting rank_bm25
  Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Collecting transformers<5.0.0,>=4.6.0 (from sentence-transformers)
  Downloading transformers-4.34.0-py3-none-any.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 23.9 MB/s eta 0:00:00
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.0.1+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.15.2+cu118)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.23.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.11.3)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (3.8.1)
Collecting sentencepiece (from sentence-transformers)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.7 MB/s eta 0:00:00
Collecting huggingface-hub>=0.4.0 (from sentence-transformers)
  Downloading huggingface_hub-0.18.0-py3-none-any.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 32.7 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (3.12.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->sentence-transformers) (3.27.6)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->sentence-transformers) (17.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (2023.6.3)
Collecting tokenizers<0.15,>=0.14 (from transformers<5.0.0,>=4.6.0->sentence-transformers)
  Downloading tokenizers-0.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 66.3 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers<5.0.0,>=4.6.0->sentence-transformers)
  Downloading safetensors-0.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 15.1 MB/s eta 0:00:00
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence-transformers) (9.4.0)
Collecting huggingface-hub>=0.4.0 (from sentence-transformers)
  Downloading huggingface_hub-0.17.3-py3-none-any.whl (295 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 34.4 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence-transformers) (1.3.0)
Building wheels for collected packages: sentence-transformers
  Building wheel for sentence-transformers (setup.py) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=df4c7454c04627986f8436ef6334ee076d9e9e6fba8158c076c641f0fb5ce09b
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers
Installing collected packages: sentencepiece, safetensors, rank_bm25, huggingface-hub, tokenizers, transformers, sentence-transformers
Successfully installed huggingface-hub-0.17.3 rank_bm25-0.2.2 safetensors-0.4.0 sentence-transformers-2.2.2 sentencepiece-0.1.99 tokenizers-0.14.1 transformers-4.34.0

In [2]:
import json
from sentence_transformers import SentenceTransformer, CrossEncoder, util
import gzip
import os
import torch

if not torch.cuda.is_available():
    print("Warning: No GPU found. Please add GPU to your notebook")

bi_encoder = SentenceTransformer('multi-qa-MiniLM-L6-cos-v1')
#reduce long passages to 256 tokens
bi_encoder.max_seq_length = 256
#number of passages retrieved by bi-encoder
top_k = 200

#cross-encoder for re-ranking the results
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

Downloading (…)5fedf/.gitattributes:   0%|          | 0.00/737 [00:00<?, ?B/s]

Downloading (…)_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading (…)2cb455fedf/README.md:   0%|          | 0.00/11.5k [00:00<?, ?B/s]

Downloading (…)b455fedf/config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading (…)ce_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading (…)edf/data_config.json:   0%|          | 0.00/25.5k [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading (…)nce_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading (…)5fedf/tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/383 [00:00<?, ?B/s]

Downloading (…)fedf/train_script.py:   0%|          | 0.00/13.8k [00:00<?, ?B/s]

Downloading (…)2cb455fedf/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)455fedf/modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [3]:
# Load requirements text data (corpus) for case study 1
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Input_corpus_uc2.xlsx to Input_corpus_uc2.xlsx
User uploaded file "Input_corpus_uc2.xlsx" with length 45445 bytes

In [4]:
import pandas as pd
df_uc1 = pd.read_excel('Input_corpus_uc2.xlsx')
df_uc1.head()

                                    requirement_text
0  A reporting entity must take the action set ou...
1  The identity card must\n\n                    ...
2  The AUSTRAC CEO must issue an identity card to...
3    An authorised officer is not entitled to exe...
4  The pecuniary penalty payable by a body corpor...

In [5]:
# transform to list of strings for case study 1
req_paras_uc1 = df_uc1['requirement_text'].tolist()
print("Passages:", len(req_paras_uc1))
print(req_paras_uc1[0])

Passages: 311
A reporting entity must take the action set out in paragraph 6.1.3 if:

(1)               the reporting entity suspects on reasonable grounds that the customer is not the person that customer claims to be; or

(2)               the reporting entity has doubts about the veracity or adequacy of documents or information previously obtained for the purpose of identifying or verifying:

(a)        the customer; and

(b)       the beneficial owner of the customer (if any); and

(c)        a person purporting to act on behalf of the customer (if any).

In [6]:
# encode all passages into vector space
corpus_embeddings = bi_encoder.encode(req_paras_uc1, convert_to_tensor=True, show_progress_bar=True)

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

In [7]:
# preparation of corpus for bm25 algo

from rank_bm25 import BM25Okapi
from sklearn.feature_extraction import _stop_words
import string
from tqdm.autonotebook import tqdm
import numpy as np


# pre-processing corpus: lower case + remove stop-words
def bm25_tokenizer(text):
    tokenized_doc = []
    for token in text.lower().split():
        token = token.strip(string.punctuation)

        if len(token) > 0 and token not in _stop_words.ENGLISH_STOP_WORDS:
            tokenized_doc.append(token)
    return tokenized_doc


tokenized_corpus = []
for passage in tqdm(req_paras_uc1):
    tokenized_corpus.append(bm25_tokenizer(passage))

bm25 = BM25Okapi(tokenized_corpus)

  0%|          | 0/311 [00:00<?, ?it/s]

In [8]:
# main relevancy ranking function (based on process info (query)) for bm25

def search_bm25(n, query):

    ##### BM25 (lexical search) + Cross-Encoder #####
    bm25_scores = bm25.get_scores(bm25_tokenizer(query))
    top_n = np.argpartition(bm25_scores, -n)[-n:]
    bm25_hits = [{'corpus_id': idx, 'score': bm25_scores[idx]} for idx in top_n]
    bm25_hits = sorted(bm25_hits, key=lambda x: x['score'], reverse=True)

    # Re-Ranking all retrieved passages with the cross_encoder #
    bm25_cross_inp = [[query, req_paras_uc1[hit['corpus_id']]] for hit in bm25_hits]
    bm25_cross_scores = cross_encoder.predict(bm25_cross_inp)
    # Sort results by the cross-encoder scores
    for idx in range(len(bm25_cross_scores)):
        bm25_hits[idx]['cross-score'] = bm25_cross_scores[idx]

    # Output of top hits from re-ranker
    bm25_hits = sorted(bm25_hits, key=lambda x: x['cross-score'], reverse=True)
    data_list_bm25 = []
    for hit in bm25_hits[0:n]:
        data_list_bm25_new = [query, req_paras_uc1[hit['corpus_id']].replace("\n", " "), hit['cross-score']]
        data_list_bm25.append(data_list_bm25_new)

    return data_list_bm25

In [9]:
# main relevancy ranking function (based on process info (query)) for bi-encoder

def search_bi(n, query):

    ##### Bi-Encoder (semantical search) + Cross-Encoder #####
    # Encoding the query using the bi-encoder and find potentially relevant passages
    question_embedding = bi_encoder.encode(query, convert_to_tensor=True)
    question_embedding = question_embedding.cuda()
    hits = util.semantic_search(question_embedding, corpus_embeddings, top_k=top_k)
    hits = hits[0]  # Get the hits for the first query

    # Re-Ranking all retrieved passages with the cross_encoder #
    cross_inp = [[query, req_paras_uc1[hit['corpus_id']]] for hit in hits]
    cross_scores = cross_encoder.predict(cross_inp)
    # Sort results by the cross-encoder scores
    for idx in range(len(cross_scores)):
        hits[idx]['cross-score'] = cross_scores[idx]

    # Output of top hits from re-ranker
    hits = sorted(hits, key=lambda x: x['cross-score'], reverse=True)
    data_list_bi = []
    for hit in hits[0:n]:
        data_list_new = [query, req_paras_uc1[hit['corpus_id']].replace("\n", " "), hit['cross-score']]
        data_list_bi.append(data_list_new)

    return data_list_bi

# PROCESS LEVEL [1]

In [10]:
# for process level, 49 passages are true relevant, thus the top 100 relevant ranked passages are retrieved

data_list_bm25 = search_bm25(100, query = "Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.")
data_list_bi = search_bi(100, query = "Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.")
print (data_list_bm25)

# create data frames and save to excel
df_1 = pd.DataFrame(data_list_bm25, columns=['query','rel_text','score'])
df_2 = pd.DataFrame(data_list_bi, columns=['query','rel_text','score'])

with pd.ExcelWriter("new_uc2_process_level_algo_output.xlsx") as writer:
    df_1.to_excel(writer, sheet_name="BM25_CE", index=False)
    df_2.to_excel(writer, sheet_name="Bi-Encoder_CE", index=False)

[["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An exemption does not apply if the reporting entity determines that it must obtain and verify any KYC information about a customer in accordance with its enhanced customer due diligence program and customer identification program.', -0.4046742], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must include a procedure for the reporting entity to verify, at a minimum, the following KYC information about a customer:  (1)      the customer’s full name; and  (2)      either:  (a)  the customer’s date of birth; or  (b)  the customer’s residential address.', -0.99596494], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", ' The reporting entity must, as soon as practicable, take reasonable measures to:  (1)               obtain and verify additional KYC information; or  (2)               update and verify existing KYC information;  so that the reporting entity is reasonably satisfied that the customer, beneficial owner or person purporting to act on behalf of the customer is the person that the customer, beneficial owner or person purporting to act on behalf of the customer claims to be.  Note:       A reporting entity is not required to take any measures that would contravene the tipping off offence in section 123 of the Act.', -1.0180249], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must include appropriate risk‑based systems and controls for the reporting entity to determine whether, in addition to the KYC information referred to in paragraph 4.2.6 above, any other KYC information collected about the customer should be verified from reliable and independent documentation, reliable and independent electronic data or a combination of the two.', -1.2271153], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must include appropriate risk‑based systems and controls for the reporting entity to respond to any discrepancy that arises in the course of verifying KYC information collected about a customer so that the reporting entity can determine whether it is reasonably satisfied that the customer is the person that he or she claims to be.', -1.3208203], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must include appropriate risk‑based systems and controls for the reporting entity to determine whether, in addition to the KYC information referred to in paragraph 4.3.5, any other KYC information referred to in paragraph 4.3.3 or other KYC information relating to the company’s existence collected in respect of the company, should be verified.', -1.3966893], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must include a procedure for the reporting entity to collect, at a minimum, the following KYC information about an individual (other than an individual who notifies the reporting entity that he or she is a customer of the reporting entity in his or her capacity as a sole trader):  (1)      the customer’s full name;  (2)      the customer’s date of birth; and  (3)      the customer’s residential address.', -1.490102], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", ' An AML/CTF program must include appropriate risk‑based systems and controls for the reporting entity to determine whether, in addition to the KYC information referred to in paragraph 4.2.3 or 4.2.4 above, any other KYC information will be collected about a customer.', -1.5269704], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must include a procedure for the reporting entity to collect at a minimum, the following KYC information about a customer who notifies the reporting entity that he or she is a customer of the reporting entity in his or her capacity as a sole trader:  (1)      the customer’s full name;  (2)      the customer’s date of birth;  (3)      the full business name (if any) under which the customer carries on his or her business;  (4)      the full address of the customer’s principal place of business (if any) or the customer’s residential address; and  (5)      any ABN issued to the customer.', -1.7171232], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'If a reporting entity is unable to establish the identity of a customer using the applicable customer identification requirements specified in Chapter 4 of the AML/CTF Rules because the customer does not possess, and is unable to obtain, the necessary information or evidence of identity, then it may use alternative identity proofing processes, in accordance with its risk-based systems and controls, to do so.', -1.7290125], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'A reporting entity must apply appropriate levels of ongoing customer due diligence in order to identify, mitigate and manage any ML/TF risk associated with customer identities established using self-attestation.  ', -2.0572097], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must include appropriate risk‑based systems and controls for the reporting entity to determine:  (1)      whether the electronic data is reliable and independent, taking into account the following factors:  (a)    the accuracy of the data;  (b)    how secure the data is;  (c)    how the data is kept up‑to‑date;  (d)   how comprehensive the data is (for example, by reference to the range of persons included in the data and the period over which the data has been collected);  (e)    whether the data has been verified from a reliable and independent source;  (f)    whether the data is maintained by a government body or pursuant to legislation; and  (g)    whether the electronic data can be additionally authenticated; and  (2)      what reliable and independent electronic data the reporting entity will use for the purpose of verification;  (3)      the reporting entity’s pre‑defined tolerance levels for matches and errors; and  (4)      whether, and how, to confirm KYC information collected about a customer by independently initiating contact with the person that the customer claims to be.', -2.3666244], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'An AML/CTF program must require that the reporting entity be satisfied that any document from which the reporting entity verifies KYC information about an individual has not expired (other than in the case of a passport issued by the Commonwealth that expired within the preceding two years).', -2.38894], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'If a reporting entity is unable to establish the identity of a customer in accordance with paragraph 4.15.1 or 4.15.1A, then it may accept a self-attestation from the customer certifying that the information provided in relation to their identity is true and correct.', -2.5811324], ["Know Your Customer (KYC) regulations for individuals add identity checks to banks’ customer onboarding processes. The KYC process is not fully automated, so it adds to bank employees’ casework, making it one more thing to manage. In the process of creating a new bank account, personal information and documents are gathered from the individual customer, and the name and further personal information are validated through various checks and confirmations. The customer's name is also checked against a Politically Exposed Persons (PEP) database to ensure they are not high-risk individuals, and any suspicious activity is flagged for further investigation. The new customer is manually reviewed following a set of guidelines for acceptability and risk level before being onboarded, and assistance is provided in navigating their account and accessing relevant products and services.", 'Customer due diligence procedures (however described) that comply with one or more laws of a foreign country giving effect to the FATF Recommendations relating to customer due diligence and record-keeping and require the other person to: (1)     identify the customer and verify the customer’s identity using reliable and independent sources, so that the other person is satisfied that it knows who the customer is; and (2)     identify the beneficial owner of the customer and take reasonable measures to verify the identity of the beneficial owner, so that the other person is satisfied that it knows who the b

# SUBPROCESS LEVEL [2]

In [11]:
# Load process text (query) for case study 1, subprocess level
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Input_queries_medium_uc2.xlsx to Input_queries_medium_uc2.xlsx
User uploaded file "Input_queries_medium_uc2.xlsx" with length 9731 bytes

In [12]:
df_qm_uc1 = pd.read_excel('Input_queries_medium_uc2.xlsx')
df_qm_uc1.head()

                                        process_text
0  To create a new account, the required personal...
1  A customers identity is validated by verifying...
2  A customer's identity is checked against a Pol...
3  To verify an account, the accuracy of the cust...
4  To manually review a new customer, a thorough ...

In [14]:
# for the medium process level (7 subprocesses), there are between 3-18 true relevant passages for each subprocess with an average of 11 passages over the 7, thus the top 30 relevant ranked passages are retrieved

# transform query input to list of strings
queries_m_uc1 = df_qm_uc1['process_text'].tolist()
print("Passages:", len(queries_m_uc1))

# iterate through all queries for use case 1
all_query_data_list_bm25 = []
all_query_data_list_bi = []
for query in queries_m_uc1:
  data_list_bm25_new = search_bm25(30, query)
  all_query_data_list_bm25.extend(data_list_bm25_new)
  data_list_bi_new = search_bi(30, query)
  all_query_data_list_bi.extend(data_list_bi_new)

# create data frames and save to excel
df_1 = pd.DataFrame(all_query_data_list_bm25, columns=['query','rel_text','score'])
df_2 = pd.DataFrame(all_query_data_list_bi, columns=['query','rel_text','score'])

with pd.ExcelWriter("new_uc2_subprocess_level_algo_output.xlsx") as writer:
    df_1.to_excel(writer, sheet_name="BM25_CE", index=False)
    df_2.to_excel(writer, sheet_name="Bi-Encoder_CE", index=False)

Passages: 7

# TASK/EVENT LEVEL [3]

In [15]:
# Load process text (query) for case study 1, subprocess level
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Input_queries_low_uc2.xlsx to Input_queries_low_uc2.xlsx
User uploaded file "Input_queries_low_uc2.xlsx" with length 9714 bytes

In [16]:
df_ql_uc1 = pd.read_excel('Input_queries_low_uc2.xlsx')
df_ql_uc1.head()

                                        process_text
0  Collect all the necessary personal information...
1  Enter the customer's information into the bank...
2  Create a unique account number for the new cus...
3  Verify the customer's full name using a govern...
4  Verify the customer's required personal inform...

In [17]:
# for the detailed process level (31 tasks/throwing events), there are between 0-9 true relevant passages for each task with an average of 4 passages over the 31, thus the top 15 relevant ranked passages are retrieved

# transform query input to list of strings
queries_l_uc1 = df_ql_uc1['process_text'].tolist()
print("Passages:", len(queries_l_uc1))

# iterate through all queries for use case 1
all_query_data_list_bm25 = []
all_query_data_list_bi = []
for query in queries_l_uc1:
  data_list_bm25_new = search_bm25(15, query)
  all_query_data_list_bm25.extend(data_list_bm25_new)
  data_list_bi_new = search_bi(15, query)
  all_query_data_list_bi.extend(data_list_bi_new)

# create data frames and save to excel
df_1 = pd.DataFrame(all_query_data_list_bm25, columns=['query','rel_text','score'])
df_2 = pd.DataFrame(all_query_data_list_bi, columns=['query','rel_text','score'])

with pd.ExcelWriter("new_uc2_event_level_algo_output.xlsx") as writer:
    df_1.to_excel(writer, sheet_name="BM25_CE", index=False)
    df_2.to_excel(writer, sheet_name="Bi-Encoder_CE", index=False)

Passages: 19